FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    default-mysql-client \
    git \
    zip \
    curl \
    sudo \
    nano \
    cron \
    nginx \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

WORKDIR /var/www/html/

COPY requirements.txt ./

RUN pip install -r requirements.txt


COPY . .

RUN useradd appuser && chown -R appuser /var/www/html
USER appuser


EXPOSE 2000
# EXPOSE 443

CMD ["python", "manage.py", "runserver", "0.0.0.0:2000"]