FROM python:3.7

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    default-mysql-client \
    curl \
    zip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

WORKDIR /var/www/html/

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .