version: '3.7'
services:
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE="tokencredit"
        container_name: db
        expose:
            - '3306'
        ports:
            - 3306:3306

        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'localhost',
                    '-u',
                    'root',
                    '-p$$MYSQL_ROOT_PASSWORD',
                ]
            timeout: 20s
            retries: 10

    web:
        build:
            context: '.'
            dockerfile: Dockerfile.ci

        container_name: tokencredit_ci
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=tokencredit
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - USE_AWS=False
        depends_on:
            db:
                condition: service_healthy
