# Generated by Django 3.1.2 on 2020-10-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE users AUTO_INCREMENT = 50000'
        ),
    ]
