# Generated by Django 3.1.2 on 2020-10-28 15:06

from django.db import migrations
from support.storages import default_backend
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201028_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(
                blank=True, null=True, storage=default_backend, upload_to='avatars', verbose_name='Profile Picture'),
        ),
    ]
