# Generated by Django 3.0.2 on 2020-02-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=191)),
                ('subject', models.CharField(max_length=191)),
                ('message', models.TextField(help_text='Please do not put a beginning salutation like dear ..., or closing greetings like regards as this will be taken care of. \n<br />            However, you can use the following anywhere to reference values: <br />\n            {{ applicant_name }} : Add appplicant name  <br />\n              {{ institution }} : The institution applied for if any           You can use HTML')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
