'''
File: 0003_auto_20201028_1548.py
Project: token-credit-backend
File Created: Wednesday, 28th October 2020 3:48:42 pm
Author: Temitayo Bodunrin (temitayo@camelcase.co)
-----
Last Modified: Wednesday, 28th October 2020 3:48:55 pm
Modified By: Temitayo Bodunrin (temitayo@camelcase.co)
-----
Copyright 2020, CamelCase Technologies Ltd
'''

# Generated by Django 3.1.2 on 2020-10-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_emailtemplate'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER table `support_emailtemplate` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
        ),
        migrations.RunSQL(
            'ALTER table `support_sitesetting` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
        ),
    ]
